import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { ICClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import type { Account } from '../src/config.js';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * `@chrischall/mcp-utils` 2.9.0 recognises an edge's refusal page, but only
 * from what the thrown error carries. These run the REAL client against
 * CloudFront's block page, so they fail if the client drops the body the
 * shared classifier reads — on the data probe, and on the verify.jsp login a
 * cold healthcheck runs first.
 */

const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

const ACCOUNT: Account = {
  name: 'anoka',
  baseUrl: 'https://anoka.infinitecampus.org',
  district: 'anoka',
  username: 'u',
  password: 'p',
};

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function loggedIn(): Response {
  return new Response('<AUTHENTICATION>success</AUTHENTICATION>', {
    status: 200,
    headers: { 'set-cookie': 'JSESSIONID=s1; Path=/' },
  });
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint?: string;
}

async function healthcheck(client: ICClient): Promise<Result> {
  const h = await createTestHarness((server) =>
    registerHealthcheckTools(server, { account: ACCOUNT, source: 'env', configError: null, client }),
  );
  const res = await h.client.callTool({ name: 'ic_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

/** Route the stubbed fetch by URL: login, CUPS discovery, and the data probe. */
function route(handlers: { login: () => Response; probe: () => Response }) {
  vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
    const url = String(input instanceof Request ? input.url : input);
    if (url.includes('/campus/verify.jsp')) return handlers.login();
    if (url.includes('linkedAccounts')) return json({ accounts: [] });
    if (url.includes('/campus/api/portal/students')) return handlers.probe();
    throw new Error(`unexpected fetch ${url}`);
  });
}

describe('ic_healthcheck on a CDN/WAF block', () => {
  beforeEach(() => vi.restoreAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it('reports edge_blocked when the data probe gets CloudFront’s block page', async () => {
    route({ login: loggedIn, probe: blocked });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('reports edge_blocked when the verify.jsp login gets CloudFront’s block page', async () => {
    route({ login: blocked, probe: () => json([]) });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('does not call an ordinary 403 from the portal an edge block', async () => {
    route({ login: loggedIn, probe: () => json({ error: 'forbidden' }, 403) });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });

  it('keeps a bounded excerpt of the body on the thrown error', async () => {
    route({ login: loggedIn, probe: () => new Response('x'.repeat(10_000), { status: 403 }) });
    const err = await new ICClient(ACCOUNT)
      .request('anoka', '/campus/api/portal/students')
      .catch((e: unknown) => e as { bodyPreview?: string });
    expect(typeof err.bodyPreview).toBe('string');
    expect(err.bodyPreview!.length).toBeLessThanOrEqual(600);
  });
});
