import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { mkdtemp, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { ICClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';
import type { Account } from '../src/config.js';

/**
 * A CDN/WAF block is not a rejected credential (chrischall/mcp-host#1015).
 *
 * `@chrischall/mcp-utils` 2.9.0 recognises an edge's refusal page, but only
 * from what the thrown error carries. These run the REAL client against
 * CloudFront's block page, so they fail if the client drops the body the
 * shared classifier reads — on the data probe, and on the verify.jsp login a
 * cold healthcheck runs first.
 */

const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  "Request blocked. We can't connect to the server for this app or website at this time. " +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

const ACCOUNT: Account = {
  name: 'anoka',
  baseUrl: 'https://anoka.infinitecampus.org',
  district: 'anoka',
  username: 'u',
  password: 'p',
};

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function loggedIn(): Response {
  return new Response('<AUTHENTICATION>success</AUTHENTICATION>', {
    status: 200,
    headers: { 'set-cookie': 'JSESSIONID=s1; Path=/' },
  });
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

interface Result {
  ok: boolean;
  error?: { kind: string; message: string };
  hint?: string;
}

async function healthcheck(client: ICClient): Promise<Result> {
  const h = await createTestHarness((server) =>
    registerHealthcheckTools(server, { account: ACCOUNT, source: 'env', configError: null, client }),
  );
  const res = await h.client.callTool({ name: 'ic_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

/** Route the stubbed fetch by URL: login, CUPS discovery, and the data probe. */
function route(handlers: { login: () => Response; probe: () => Response }) {
  vi.spyOn(globalThis, 'fetch').mockImplementation(async (input) => {
    const url = String(input instanceof Request ? input.url : input);
    if (url.includes('/campus/verify.jsp')) return handlers.login();
    if (url.includes('linkedAccounts')) return json({ accounts: [] });
    if (url.includes('/campus/api/portal/students')) return handlers.probe();
    throw new Error(`unexpected fetch ${url}`);
  });
}

describe('ic_healthcheck on a CDN/WAF block', () => {
  beforeEach(() => vi.restoreAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it('reports edge_blocked when the data probe gets CloudFront’s block page', async () => {
    route({ login: loggedIn, probe: blocked });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('reports edge_blocked when the verify.jsp login gets CloudFront’s block page', async () => {
    route({ login: blocked, probe: () => json([]) });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('reports edge_blocked, not an expired session, when the data probe gets a 401 refusal page', async () => {
    // mcp-utils 2.10 returns a 401 refusal page from withSession untouched
    // (no re-login). It must not then be dressed as SessionExpiredError.
    route({
      login: loggedIn,
      probe: () => new Response(CLOUDFRONT_BLOCK, { status: 401, headers: { 'content-type': 'text/html' } }),
    });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
  });

  it('does not re-login or throw SessionExpiredError on a 401 refusal page', async () => {
    let logins = 0;
    route({
      login: () => { logins++; return loggedIn(); },
      probe: () => new Response(CLOUDFRONT_BLOCK, { status: 401, headers: { 'content-type': 'text/html' } }),
    });
    const err = await new ICClient(ACCOUNT)
      .request('anoka', '/campus/api/portal/students')
      .catch((e: unknown) => e as Error & { bodyPreview?: string });
    expect(err.name).not.toBe('SessionExpiredError');
    expect(err.message).toMatch(/IC 401/);
    expect(err.bodyPreview).toMatch(/could not be satisfied/);
    expect(logins).toBe(1);
  });

  it('treats a 401 whose body cannot be read as an expired session, not a block', async () => {
    // Nothing shows it is a refusal page, so the ordinary expiry path runs:
    // re-login, one replay, then SessionExpiredError.
    const unreadable401 = () =>
      new Response(new ReadableStream({ pull(c) { c.error(new Error('stream reset')); } }), { status: 401 });
    let logins = 0;
    route({ login: () => { logins++; return loggedIn(); }, probe: unreadable401 });
    const err = await new ICClient(ACCOUNT)
      .request('anoka', '/campus/api/portal/students')
      .catch((e: unknown) => e as Error);
    expect(err.name).toBe('SessionExpiredError');
    expect(logins).toBe(2);
  });

  it('does not call an ordinary 403 from the portal an edge block', async () => {
    route({ login: loggedIn, probe: () => json({ error: 'forbidden' }, 403) });
    const r = await healthcheck(new ICClient(ACCOUNT));
    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });

  it('keeps a bounded excerpt of the body on the thrown error', async () => {
    route({ login: loggedIn, probe: () => new Response('x'.repeat(10_000), { status: 403 }) });
    const err = await new ICClient(ACCOUNT)
      .request('anoka', '/campus/api/portal/students')
      .catch((e: unknown) => e as { bodyPreview?: string });
    expect(typeof err.bodyPreview).toBe('string');
    expect(err.bodyPreview!.length).toBeLessThanOrEqual(600);
  });

  it('still throws the status error when the failed response body cannot be read', async () => {
    // A body that errors mid-read must not replace the HTTP failure with a
    // stream error: the status line is what the caller branches on.
    const unreadable = new Response('', { status: 404, statusText: 'Not Found' });
    vi.spyOn(unreadable, 'text').mockRejectedValue(new Error('stream reset'));
    route({ login: loggedIn, probe: () => unreadable });
    const err = await new ICClient(ACCOUNT)
      .request('anoka', '/campus/api/portal/students')
      .catch((e: unknown) => e as Error & { bodyPreview?: string });
    expect(err.message).toMatch(/IC 404 Not Found/);
    expect(err.bodyPreview).toBe('');
  });
});

// Cloudflare's managed-challenge interstitial, as served in front of an origin.
const CLOUDFLARE_CHALLENGE =
  '<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>' +
  '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>' +
  '<div class="main-wrapper" role="main"><div class="main-content"><noscript>' +
  '<div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div>' +
  '</noscript></div></div><script>(function(){window._cf_chl_opt={cvId: \'3\',cZone: \'anoka.infinitecampus.org\'};' +
  "var a = document.createElement('script');a.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1';" +
  '}());</script></body></html>';

describe('ICClient.download on a CDN/WAF block (chrischall/mcp-host#1015)', () => {
  let dir: string;
  beforeEach(async () => {
    vi.restoreAllMocks();
    dir = await mkdtemp(join(tmpdir(), 'ic-edge-dl-'));
  });
  afterEach(async () => {
    vi.restoreAllMocks();
    await rm(dir, { recursive: true, force: true });
  });

  /** Route login/discovery, and serve each download from `downloads` in turn. */
  function routeDownload(downloads: Array<() => Response>) {
    const state = { logins: 0, cookies: [] as string[] };
    vi.spyOn(globalThis, 'fetch').mockImplementation(async (input, init) => {
      const url = String(input instanceof Request ? input.url : input);
      if (url.includes('/campus/verify.jsp')) {
        state.logins++;
        return new Response('<AUTHENTICATION>success</AUTHENTICATION>', {
          status: 200,
          headers: { 'set-cookie': `JSESSIONID=s${state.logins}; Path=/` },
        });
      }
      if (url.includes('linkedAccounts')) return json({ accounts: [] });
      if (url.includes('/campus/doc')) {
        state.cookies.push(((init?.headers ?? {}) as Record<string, string>).Cookie ?? '');
        const next = downloads.shift();
        if (!next) throw new Error('no more download responses');
        return next();
      }
      throw new Error(`unexpected fetch ${url}`);
    });
    return state;
  }

  const pdf = () => new Response(new Uint8Array([1, 2, 3]), { status: 200, headers: { 'content-type': 'application/pdf' } });

  it('throws EdgeBlockedError, not SessionExpiredError, on a 401 CloudFront refusal page', async () => {
    const state = routeDownload([
      () => new Response(CLOUDFRONT_BLOCK, { status: 401, headers: { 'content-type': 'text/html' } }),
    ]);
    const err = await new ICClient(ACCOUNT)
      .download('anoka', '/campus/doc', join(dir, 'a.pdf'))
      .catch((e: unknown) => e as Error);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect(err.name).not.toBe('SessionExpiredError');
    expect((err as EdgeBlockedError).vendor).toBe('CloudFront');
    expect((err as EdgeBlockedError).status).toBe(401);
    expect(err.message).not.toMatch(/Session expired|IC_USERNAME|IC_PASSWORD/);
    // No re-login was spent on it, and nothing was written.
    expect(state.logins).toBe(1);
    await expect(stat(join(dir, 'a.pdf'))).rejects.toThrow(/ENOENT/);
  });

  it('keeps the stored session through a 401 block: the next download reuses it with no re-login', async () => {
    const state = routeDownload([
      () => new Response(CLOUDFRONT_BLOCK, { status: 401, headers: { 'content-type': 'text/html' } }),
      pdf,
    ]);
    const client = new ICClient(ACCOUNT);
    await expect(client.download('anoka', '/campus/doc', join(dir, 'a.pdf'))).rejects.toBeInstanceOf(EdgeBlockedError);
    const meta = await client.download('anoka', '/campus/doc', join(dir, 'b.pdf'));
    expect(meta.bytes).toBe(3);
    expect(state.logins).toBe(1);
    expect(state.cookies).toEqual(['JSESSIONID=s1', 'JSESSIONID=s1']);
  });

  it('throws EdgeBlockedError on a 403 Cloudflare challenge page', async () => {
    routeDownload([
      () => new Response(CLOUDFLARE_CHALLENGE, {
        status: 403,
        headers: { 'content-type': 'text/html; charset=UTF-8', 'cf-mitigated': 'challenge', server: 'cloudflare' },
      }),
    ]);
    const err = await new ICClient(ACCOUNT)
      .download('anoka', '/campus/doc', join(dir, 'a.pdf'))
      .catch((e: unknown) => e as Error);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe('Cloudflare');
  });

  it('control: a genuine 401 from IC is still an expired session (re-login, one replay, then SessionExpiredError)', async () => {
    const state = routeDownload([
      () => new Response('', { status: 401 }),
      () => new Response('', { status: 401 }),
    ]);
    const err = await new ICClient(ACCOUNT)
      .download('anoka', '/campus/doc', join(dir, 'a.pdf'))
      .catch((e: unknown) => e as Error);
    expect(err.name).toBe('SessionExpiredError');
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect(state.logins).toBe(2);
  });

  it('control: an ordinary non-block 403 keeps the plain download status error', async () => {
    routeDownload([() => json({ error: 'forbidden' }, 403)]);
    const err = await new ICClient(ACCOUNT)
      .download('anoka', '/campus/doc', join(dir, 'a.pdf'))
      .catch((e: unknown) => e as Error);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect(err.message).toMatch(/IC download 403/);
  });
});
